/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_edu_zstu_facedetection_Detection_FaceDetectorr */

#ifndef _Included_cn_edu_zstu_facedetection_Detection_FaceDetector
#define _Included_cn_edu_zstu_facedetection_Detection_FaceDetector
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     cn_edu_zstu_doorservice_MainActivity
 * Method:    predict
 * Signature: (Landroid/graphics/Bitmap;[B)V
 */
JNIEXPORT jboolean JNICALL Java_cn_edu_zstu_facedetection_Detection_FaceDetector_predict
  (JNIEnv *, jobject, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
